apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gb7dp5inx-python 
  janus-idp.io/tekton: gb7dp5inx-python
  backstage.io/kubernetes-id: gb7dp5inx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gb7dp5inx-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml