apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gb7dp5inx-python-gitops
  description: This is GitOps manifest for gb7dp5inx-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gb7dp5inx-python
    backstage.io/kubernetes-id: gb7dp5inx-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gb7dp5inx-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gb7dp5inx-python
